### ISSUE TITLE
1_test.py capture_continuous stuck after first frame

### ISSUE THREAD

**Issue by heartcored98** [realizator/stereopi-tutorial#5]
Hi! 

I am using stereopi non-slim edition. I would like to stream both camera frame.
I Downloaded ready-to-use raspbian image.
Enabled camera. 

After running 1_test.py code and found that frame capturing stuck and freeze after first frame.
Also, cameras entered into a freezing mode so the led doesn't turn off even though I terminate the python process or terminal. 
The only way to escape the frozen camera is rebooting. 

I checked that simple `capture` method work well and the stereoscopic image saved with no problem. But `capture_continuous` or `capture_sequence` result always freezing. 

I really need your help

**Comment by realizator** [comment]
Hi @heartcored98!
It looks strange, as 1_test.py is a bullet-proof script I use for the first system tests.
I can suggest you have some camera connection issue. You see, camera ribbon has 15 lines, and only 2 of them are used for I2C to "speak" with camera. So if this couple is connected Ok, Raspbian sees both your cameras and can send commands. But for data flow a lot of other lines are used. So while this data transition system might have problems. 

In your case I'd follow this procedure:
1. Run "raspivid -cs 0 -o 1.h264"
If this camera 0 is Ok, you will get recorded file.
2. Run ""raspivid -cs 1 -o 2.h264"
The same thing here. I can suggest one of your cameras will not pass this test.

When you find your non-working camera, try to disconnect camera ribbon from StereoPi and camera module, and connect them again. You can also change ribbon ends (insert end from camera to StereoPi and backwards with another end).

Please check this and write me your results.

**Comment by heartcored98** [comment]
Thank you for fast reply!

I tested each camera as you suggested with raspivid command. 
However, both camera work with no problem. 
One thing to note-worthy is red led on camera number 1 is not turned-on when I select it with `-cs 1`, but the led on the camera number 0 work fine. 
Does it indicate some kinds of trouble?

**Comment by realizator** [comment]
If each camera works fine, try to capture stereoscopic image and a small video:
`raspistill -3d sbs -w 1280 -h 720 -o 3.jpg `
`raspivid -3d sbs -w 1280 -h 720 -o stereo.h264`

If your system will be able to do both things, it means that everything is Ok with cameras and the board. 

As fir the LED - it is normal mode, and only 1 LED will light up on the camera.

One more hypothesis: when capturing video in Python, system has much more loadin in comparison with raspistill or raspivid, as both of them are highly optimized. May be you have power issue. Please check your power adapter canprovide enpugh current (2A ideally). As arule in this case you can see lightning in the top right part of your screen, someting like this:
![46dd56d056b4ecde514fed9b48f2a912442a2628](https://user-images.githubusercontent.com/6445235/63855853-0611da00-c9a9-11e9-9433-8350f1a33b7b.png)

**Comment by heartcored98** [comment]
Firstly, `raspistill -3d sbs -w 1280 -h 720 -o 3.jpg` and `raspivid -3d sbs -w 1280 -h 720 -o stereo.h264` both did not work. capturing process get freezed.

About the power issue, I used ipad charger with usb adapter but it did not give me lightning logo on the display. 

Any suggestion? I think I should have to use other power adapter

**Comment by realizator** [comment]
iPad power adapter is more than enough.
As for raspistill and raspivid stuck - it's not good behavior.
Could you please try to load [SLP image](https://wiki.stereopi.com/index.php?title=SLP_(StereoPi_Livestream_Playground)_Raspbian_Image) and check, if it works in stereoscopic mode? If stereo mode will not work in it, looks like we need to replace your board.
The quickest way to check stereo in SLP image is connect it to HDMI monitor. If everything works fine, you will see pictures from both cameras on your monitor.

**Comment by heartcored98** [comment]
Hi, SLP image also did not work.
Could you please replace my board?

**Comment by realizator** [comment]
@heartcored98 Could you please send me your order number to my email @gmail.com (put my GitHub nickname right before "at" sign).

**Comment by heartcored98** [comment]
Hi @realizator, I sent the email through Gmail but cannot get any response. Could you please check my board replacement request?

**Comment by realizator** [comment]
@heartcored98 As we discussed by email, your replacement board is already shipped. Please let me know when it will arrive, and I close this issue.

**Comment by deepav-ai** [comment]
I was able to run the raspivid commands for each camera without problem. When I try running the first python script it hangs with no preview. I tried the following commands and the preview comes up but hangs, OS does not hang. However I can't get the preview to go away and even a soft reboot won't complete. 

```
raspistill -3d sbs -w 1280 -h 720 -o 3.jpg
raspivid -3d sbs -w 1280 -h 720 -o stereo.h264
```

I just reflashed with the SLP image and when I boot both images come up and it's not hanging.

**Comment by deepav-ai** [comment]
I reinstalled Buster instead of Stretch and ran the first python script and it worked fine.

**Comment by realizator** [comment]
@deepav-ai This is a known bug in the latest Raspbian firmware. New AWB algorithm occasionally broke stereoscopic support. You can find discussion here https://github.com/raspberrypi/firmware/issues/1253

At this moment, you can either use previous release of a Buster (and do not upgrade it), or use a trick with `sudo vcdbg set awb_mode 0` as a temporarily solution.

**Comment by heartcored98** [comment]
Thanks to your advice, the problem was finally solved :)
